### ISSUE TITLE
division 

### ISSUE THREAD

**Issue by Albert-21** [Albert-21/testing-calculator#4]
:sparkles: **Welcome to division** :sparkles:
We're so excited that you've decided to create a new division issues!

division uni tests
- [ ] Should divide 2 / 2 = 1
- [ ] Should divide 9 / 2 = 4.5
- [ ] Should divide 3.0 / 0.5 = 6
- [ ] Should divide 0 / 1  = 0

**Comment by Albert-210** [comment]
correcto
